name: fairDAGs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - python-graphviz=0.17
  - flask=2.0.1
  - gunicorn=20.1.0
  - numpy=1.21.0
  - pandas=1.2.5
  - scikit-learn=0.24.2
  - scipy=1.7.0
  - matplotlib=3.4.2
  - seaborn=0.11.1
  - plotly=5.1.0
